### ISSUE TITLE
error  at starting of the server

### ISSUE THREAD

**Issue by dgu123** [loowid/loowid#198]
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\webconference\loowid\node_modules\mongoose\no
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3) code: 'MODULE_NOT_FOUND' }

**Comment by juanjmerono** [comment]
It sounds like a problem with node version, did you try to start using docker?
