### ISSUE TITLE
can't open site in browser

### ISSUE THREAD

**Issue by senid231** [loowid/loowid#232]
installing
```
$ git clone https://github.com/loowid/loowid
$ cd loowid
$ git checkout 2.1.0
$ npm install --production
// after that I've install mongodb server which runs on port 27017 by default.
```
start
```
// npm start failed because ports 80 and 443 are already in use
// so I just run with overridden ports.
$ ADMIN_USERNAME=admin ADMIN_USERNAME=password MONGOLAB_URI=localhost:27017 node node_modules/grunt-cli/bin/grunt prod --port=8383 --sport=8384
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "grunt-jasmine-node" not found. Is it installed?
>> Local Npm module "grunt-jasmine-node-istanbul" not found. Is it installed?

Running "uglify:build" (uglify) task
>> 1 sourcemap created.
>> 1 file created.

Running "less:prod" (less) task
File public/css/loowid.min.css created: 183.8 kB → 157.61 kB

Running "concurrent:prod" (concurrent) task
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "grunt-jasmine-node" not found. Is it installed?
>> Local Npm module "grunt-jasmine-node-istanbul" not found. Is it installed?

Running "shell:mongo" (shell) task
>> Local Npm module "grunt-jasmine-node" not found. Is it installed?
>> Local Npm module "grunt-jasmine-node-istanbul" not found. Is it installed?

Running "nodemon:prod" (nodemon) task
Warning: Command failed: mongod --dbpath ./data
 Used --force, continuing.

Done, but with warnings.
    
    
    [nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: nothing.js
[nodemon] starting `node server.js`
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/senid/projects/forked/loowid/node_modules/mongoose/node_modules/bson/ext/index.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[2018-11-23 18:32:06.302] [WARN] server - ENOENT: no such file or directory, open 'private.pem'
connect-mongo deprecated mongoose_connection option is deprecated. Use mongooseConnection instead server.js:244:9
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
[2018-11-23 18:32:06.493] [INFO] server - Running non-openshift environment !!
[2018-11-23 18:32:06.495] [INFO] server - Express app started on 0.0.0.0 port 8383

```

I've tried to open page `127.0.0.1:8383` but it loads infinitely

curl also hangs
```
$ curl --verbose http://127.0.0.1:8383
* Rebuilt URL to: http://127.0.0.1:8383/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8383 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8383
> User-Agent: curl/7.52.1
> Accept: */*
> 

```

**Comment by senid231** [comment]
monodb logs when starting server
```
2018-11-23T18:39:57.567+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:37740 #16 (1 connection now open)
2018-11-23T18:39:57.568+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:37742 #17 (2 connections now open)
2018-11-23T18:39:57.569+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:37744 #18 (3 connections now open)
2018-11-23T18:39:57.569+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:37746 #19 (4 connections now open)
2018-11-23T18:39:57.570+0200 I NETWORK  [listener] connection accepted from 127.0.0.1:37748 #20 (5 connections now open)
```
